services:
  db:
    image: postgres:16
    container_name: rentmycar-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RentMyCar
    ports:
      - "5439:5432"
    volumes:
      - rentmycar_pgdata:/var/lib/postgresql/data
      # OPTIONAL: rulează scripturi SQL la prima inițializare
      # - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rentmycar -d RentMyCar"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rentmycar-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  rentmycar_pgdata:

